version: '2'
services:
  angular-app:
    image: ajes23/fe
    container_name: ajes/Wfe
    build: .
    ports:
      - 80:80
  mysql:
    image: mysql
    expose:
      - 3307
    ports:
      - '3307:3306'
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: user
  ajes23/be:
    image: ajes23/be
    build: .
    restart: always
    container_name: ajes23/Wbe
    ports:
      - 9090:9090
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/database?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user